import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CafeProvider } from "@/context/CafeContext";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",      
});

export const metadata = {
  title: "Landy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased bg-[#121214] text-[16px] text-[#EFEFF0]`}
      >
        <CafeProvider>{children}</CafeProvider>
      </body>
    </html>
  );
}
